volatile unsigned char rx_buf[64]={0};
volatile unsigned char btrx = 0;
volatile unsigned char bttx = 0;
volatile unsigned char ttn_cmd = 0;
volatile unsigned int u1r_buf=0;
volatile unsigned int tmp=0;
volatile unsigned int read=0;
volatile unsigned int error_dac = 0;
//volatile unsigned int row = 0;
//volatile unsigned int col = 0;
volatile int row_now = 0;
volatile int col_now = 0;
volatile unsigned int vs = 0;
//volatile unsigned int v1 = 0;
//volatile unsigned int v2 = 0;
volatile unsigned int count = 0;
volatile unsigned int count2 = 0;
//volatile unsigned int vsFlag = 0;
//volatile unsigned int out1 = 0;
volatile unsigned int count_pxon = 0;
volatile unsigned int ctr_temp = 0;
volatile long tempnew = 0;
volatile unsigned int tempavg = 0;
volatile signed int tempP = 0;
volatile signed int tempI = 0;
volatile signed int tempD = 0;
volatile signed int temperr = 0;
volatile signed long long temperr_prev = 0;
volatile signed long long temperr_prevD = 0;
volatile signed int tempdac = 0;
volatile signed int tempdac0 = 0;
volatile unsigned int vref_op = 0;
volatile unsigned int ctr_hi = 0;
volatile unsigned int ctr_low = 0;
volatile unsigned int ctr_op = 0;
volatile unsigned int step;
volatile unsigned int vref;


//static uint16_t spi_ttn_tx[1031];
//static uint16_t spi_ttn_rx[2048];
static uint16_t tempfootprint[988];
static uint16_t row_max = 78;
static uint16_t col_max = 56;
static uint16_t vreg = 730;// 10us is 1856;
//static uint16_t treg = 1856;// Reg temp px higher due to chip defect
static uint16_t tol = 20;
static int end = 0xFFFF;
static int tdacmax = 600;
static int tau63[2];
volatile unsigned int tempref = 140;//200;//100;
static int tempPk = 4;//3;
static int tempPi = 10;//7;
static int tempPkr = 2;//15//3;
static int tempPir = 6;//5//5;
static int tempPd = 1;//10//2;
static char uart_send[32];